# Generated by Django 5.2 on 2025-06-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_alter_post_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('posts', models.ManyToManyField(related_name='categories', to='post.post')),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
    ]
