# Generated by Django 5.2 on 2025-06-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='archived',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
