# Generated by Django 5.2 on 2025-05-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_alter_post_author'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='voted_posts',
            field=models.ManyToManyField(blank=True, null=True, related_name='users_voted', to='post.post'),
        ),
    ]
