# Generated by Django 5.2 on 2025-05-30 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_alter_post_author'),
        ('user', '0002_user_voted_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='voted_posts',
        ),
        migrations.AddField(
            model_name='user',
            name='down_voted_posts',
            field=models.ManyToManyField(blank=True, null=True, related_name='users_down_voted', to='post.post'),
        ),
        migrations.AddField(
            model_name='user',
            name='up_voted_posts',
            field=models.ManyToManyField(blank=True, null=True, related_name='users_up_voted', to='post.post'),
        ),
    ]
