# Generated by Django 5.2 on 2025-05-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_alter_post_author'),
        ('user', '0003_remove_user_voted_posts_user_down_voted_posts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='down_voted_comments',
            field=models.ManyToManyField(blank=True, related_name='users_down_voted', to='post.comment'),
        ),
        migrations.AddField(
            model_name='user',
            name='up_voted_comments',
            field=models.ManyToManyField(blank=True, related_name='users_up_voted', to='post.comment'),
        ),
        migrations.AlterField(
            model_name='user',
            name='down_voted_posts',
            field=models.ManyToManyField(blank=True, related_name='users_down_voted', to='post.post'),
        ),
        migrations.AlterField(
            model_name='user',
            name='up_voted_posts',
            field=models.ManyToManyField(blank=True, related_name='users_up_voted', to='post.post'),
        ),
    ]
